/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

extern "C" int racing_mpc_function(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int racing_mpc_function_alloc_mem(void);
extern "C" int racing_mpc_function_init_mem(int mem);
extern "C" void racing_mpc_function_free_mem(int mem);
extern "C" int racing_mpc_function_checkout(void);
extern "C" void racing_mpc_function_release(int mem);
extern "C" void racing_mpc_function_incref(void);
extern "C" void racing_mpc_function_decref(void);
extern "C" casadi_int racing_mpc_function_n_in(void);
extern "C" casadi_int racing_mpc_function_n_out(void);
extern "C" casadi_real racing_mpc_function_default_in(casadi_int i);
extern "C" const char* racing_mpc_function_name_in(casadi_int i);
extern "C" const char* racing_mpc_function_name_out(casadi_int i);
extern "C" const casadi_int* racing_mpc_function_sparsity_in(casadi_int i);
extern "C" const casadi_int* racing_mpc_function_sparsity_out(casadi_int i);
extern "C" int racing_mpc_function_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define racing_mpc_function_SZ_ARG 314
#define racing_mpc_function_SZ_RES 17
#define racing_mpc_function_SZ_IW 0
#define racing_mpc_function_SZ_W 37439
