/**:
  ros__parameters:
    racing_lqr:
      n: 20
      dt: 0.01

      q: [
        1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 1.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 1.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 1.0
      ]
      r: [
        1.0, 0.0, 0.0,
        0.0, 1.0, 0.0,
        0.0, 0.0, 1.0
      ]
      qf: [
        10.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 10.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 10.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 1.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 10.0
      ]

      step_mode: "continuous"
      x_max: [.inf, .inf, .inf, 100.0, 15.0, 2.0]
      x_min: [-.inf, -.inf, -.inf, 3.0, -15.0, -2.0]
      u_max: [5.0, 0.314159]
      u_min: [-10.0, -0.314159]
      max_vel_ref_diff: 3.0 # max difference between reference velocity and actual velocity