/**:
  ros__parameters:
    racing_mpc:
      max_cpu_time: 0.085
      max_iter: 200
      tol: 1e-3
      interface: opti
      n: 40
      dt: 0.025
      margin: 0.1
      average_track_width: 1.0
      verbose: false
      jit: true
      num_mpc: 1
      num_cycle_to_switch: 10
      max_extrapolate_horizon: 40

      q_contour: 1.0
      q_heading: 1.0
      q_boundary: 1000.0 # track boundary slack cost. 0 to disable (hard constraint)
      q_follow: 0.2
      q_vel: 0.2
      q_vy: 0.001
      q_vyaw: 0.001
      r: [
        0.1, 0.0,
        0.0, 0.1,
      ]
      r_d: [
        0.1, 0.0,
        0.0, 0.1,
      ]
      max_vel_ref_diff: 1.0 # max difference between reference velocity and actual velocity

      x_max: [.inf, .inf, .inf, 3.0, 1.0, 3.0]
      x_min: [-.inf, -.inf, -.inf, 0.1, -1.0, -3.0]
      u_max: [0.01, 0.33]
      u_min: [-0.01, -0.33]
      du_max: [0.02, 0.66]
      du_min: [-0.02, -0.66]

      step_mode: "continuous"

      # LMPC
      learning: true
      convex_hull_slack: [40.0, 40.0, 4.0, 40.0, 40.0, 4.0]
      num_ss_pts: 96
      num_ss_pts_per_lap: 32
      max_lap_stored: 3

      # recording
      record: false
      path_prefix: "/home/haoru/berkeley/Racing-LMPC-ROS2/src/mpc/racing_mpc/test_data/barc_ss/ss_"

      # load: true
      # load_path:
      #   - /home/haoru/berkeley/Racing-LMPC-ROS2/src/mpc/racing_mpc/test_data/barc_ss/ss_lap_1
      #   - /home/haoru/berkeley/Racing-LMPC-ROS2/src/mpc/racing_mpc/test_data/barc_ss/ss_lap_2
      #   - /home/haoru/berkeley/Racing-LMPC-ROS2/src/mpc/racing_mpc/test_data/barc_ss/ss_lap_3